baseURL = 'https://manojitnath.com/'
languageCode = 'en-us'
title = 'Manojit'

enableRobotsTXT = true

[outputs]
home = ["HTML", "RSS", "JSON", "SITEMAP", "ROBOTS"]

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[markup.highlight]
    noClasses = false

[Params]
dateFormat = "Jan 2, 2006"

[params]
  description = "Cybersecurity blog by Manojit Nath â€” covering GRC, Cloud Security, Threat Modeling and DevSecOps"

# hugo.toml or config.toml
[markup]
  [markup.tableOfContents]
    endLevel = 3    # Include headings up to H3
    ordered = false # Use <ul> instead of <ol>
    startLevel = 2  # Start with H2 headings

languageCode = "en-us"
